version: '3.8'

services:
  db:
    image: mysql:8.0.30
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_prophotostock
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    restart: always
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend_net

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: pma_container
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - backend_net

  nodejs:
    build:
      context: .
      dockerfile: nodejs.dockerfile
    container_name: backend-nodejs-1
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend_net
    command: ["npx", "nodemon", "server.mjs"]

volumes:
  dbdata:

networks:
  backend_net:
